### ISSUE TITLE
[求助]这玩意怎么用？

### ISSUE THREAD

**Issue by ruoktest** [Beipy/Pc-Black-macOS#1]
找到自己配置之后，如何用呢？

**Comment by Beipy** [comment]
就是想用Mac Os系统又不想买苹果电脑的人用的，需要做苹果硬件的引导。来模拟绕过Os系统的检测硬件真实性，需要用U盘、也就是重装系统，一个笔记本如果网卡支持免驱动，可以做成黑苹果很方便，双系统还可以。详情参考一下链接安装：https://blog.csdn.net/czjlghndcy/article/details/83187641

**Comment by Beipy** [comment]
下载Mos镜像，替换镜像内的EFI引导文件。
