### ISSUE TITLE
怎么下载不了啊？

### ISSUE THREAD

**Issue by 10807428** [Beipy/Pc-Black-macOS#3]
我没有找到下载按钮啊！

**Comment by Beipy** [comment]
Clone or download这个按钮可以直接下载，压缩文件到本地

**Comment by 10807428** [comment]
下载好了。也装好了。非常感谢



------------------ 原始邮件 ------------------
发件人: "Beipy"<notifications@github.com>; 
发送时间: 2019年7月12日(星期五) 下午4:24
收件人: "Beipy/Mac-Hackintosh-Clover"<Mac-Hackintosh-Clover@noreply.github.com>; 
抄送: "新月"<10807428@qq.com>; "Author"<author@noreply.github.com>; 
主题: Re: [Beipy/Mac-Hackintosh-Clover] 怎么下载不了啊？ (#3)




Clone or download这个按钮可以直接下载，压缩文件到本地
